### ISSUE TITLE
Invalid response, getPlayingContentInfo

### ISSUE THREAD

**Issue by mories76** [gerard33/sony-bravia-ha#4]
Hi Gerard,

I am using this component with Home Assistant, and I have/had the following error message when Netfix is running on my TV.
```
2018-12-23 10:48:48 ERROR (SyncWorker_6) [braviapsk.sony_bravia_psk] Invalid response: {'error': [7, 'Illegal State'], 'id': 1}
  request path: sony/avContent
  request params: {"method": "getPlayingContentInfo", "params": [], "id": 1, "version": "1.0"}
```

In my research I see that the requirement for this component is as follows
`REQUIREMENTS = ['pySonyBraviaPSK==0.3.1']`

But I cannot find where the source for this package is. Your own version sony_bravia_psk only seems to go to version 2.3.
I would like to request a change to this component, changing line 245
from 
`resp = self.bravia_req_json("sony/avContent", self._jdata_build("getPlayingContentInfo", None))`
to
`resp = self.bravia_req_json("sony/avContent", self._jdata_build("getPlayingContentInfo", None), False)`
Solved my logging issue.

Could you point me in the right direction, so maybe I can submit a PR
Thanks

**Comment by gerard33** [comment]
This repo is using a test version which combines PSK and PIN. I did some development on that a while ago, but it is not really maintained lately.
I would advise to use this [version](https://github.com/custom-components/media_player.braviatv_psk) (PSK only).

The `pySonyBraviaPSK` is hosted on PyPi, where `0.1.7` is used in the PSK only component and `0.3.1` in the PSK and PIN component.

Can you first try the other version to see if the issue is also there?
Do you have a Bravia with Android TV? I don't and have never seen that error before.

**Comment by mories76** [comment]
The version you adviced is working, and yes I do have and Android TV for which both PSK and PIN should work.
And I am willing to do some testing.
It would be nice if Home Assistant just working with both pin and psk versions.
I saw that some of your changes were commited upstream to aparraga's version.
